
#define KEY_PAUSE			CTRL_S
#define KEY_QUIT			CTRL_Q
#define KEY_ATTACK			'a'
#define KEY_ZERO			'z'
#define KEY_UNMANAGE			'c'
#define KEY_PARATROOPS			'p'
#define KEY_PARATROOPS_MANAGE		'P'
#define KEY_ARTILLERY			'g'
#define KEY_ARTILLERY_MANAGE		'G'
#define KEY_DIG				'd'
#define KEY_DIG_MANAGE			'D'
#define KEY_FILL			'f'
#define KEY_FILL_MANAGE			'F'
#define KEY_BUILD			'b'
#define KEY_BUILD_MANAGE		'B'
#define KEY_SCUTTLE			's'
#define KEY_STEP			'q'

#define KEY_DIR_0			'i'
#define KEY_DIR_1			'j'
#define KEY_DIR_2			'm'
#define KEY_DIR_3			'k'
#define KEY_DIR_4			'l'
#define KEY_DIR_5			'o'
